name: Codecov Coverage
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Build & generate coverage report
        run: |
          yarn
          yarn test
      - name: Upload coverage
        if: success()
        uses: codecov/codecov-action@v2
